server:
  port: 9090

---
spring:
  config:
    activate:
      on-profile: k8s

eureka:
  client:
    serviceUrl:
      # Utilise le Service Kubernetes "discovery-server"
      defaultZone: http://discovery-server:8761/eureka/
