server:
  port: 9090

---
spring:
  config:
    activate:
      on-profile: k8s

server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    hostname: admin-server
    preferIpAddress: false
    instance-id: ${spring.application.name}:${random.uuid}

management:
  zipkin:
    tracing:
      endpoint: http://tracing-server:9411/api/v2/spans
