zuul:
  prefix: /api
  ignoredServices: '*'
  routes:
    vets-service: /vet/**
    visits-service: /visit/**
    customers-service: /customer/**
    api-gateway: /gateway/**

server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,text/css,application/javascript
    min-response-size: 2048

spring:
  messages:
    basename: messages/messages

---
spring:
  config:
    activate:
      on-profile: k8s

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    hostname: api-gateway
    preferIpAddress: false
    instance-id: ${spring.application.name}:${random.uuid}

management:
  zipkin:
    tracing:
      endpoint: http://tracing-server:9411/api/v2/spans
