# COMMON APPLICATION PROPERTIES

server:
  port: 0
  shutdown: graceful

spring:
  sql:
    init:
      schema-locations: classpath*:db/hsqldb/schema.sql
      data-locations: classpath*:db/hsqldb/data.sql
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    config:
      allow-override: true
      override-none: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none

management.security.enabled: false
management.endpoints.web.exposure.include: "*"
spring.cloud.refresh.refreshable: false

logging.level.org.springframework: INFO

management:
  endpoint:
    metrics.enabled: true
    prometheus.enabled: true
  endpoints:
    web.exposure.include: '*'
  metrics:
    export.prometheus.enabled: true
  tracing:
    sampling.probability: 1

---
spring:
  config:
    activate:
      on-profile: chaos-monkey      
management.endpoint.chaosmonkey.enabled: true
chaos:
  monkey:
    enabled: true
    watcher:
      component: false
      controller: false
      repository: false
      rest-controller: false
      service: false

---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/petclinic?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: petclinic
  sql:
    init:
      schema-locations: classpath*:db/mysql/schema.sql
      data-locations: classpath*:db/mysql/data.sql
      mode: ALWAYS

---
spring:
  config:
    activate:
      on-profile: k8s
  datasource:
    url: jdbc:mysql://mysql-server-petclinic:3306/petclinic?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: petclinic
  sql:
    init:
      schema-locations: classpath*:db/mysql/schema.sql
      data-locations: classpath*:db/mysql/data.sql
      mode: ALWAYS
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
management:
  zipkin:
    tracing:
      endpoint: http://tracing-server:9411/api/v2/spans
