spring:
  config:
    activate:
      on-profile: default
eureka:
  instance:
    # permet d’enregistrer plusieurs instances avec des ports dynamiques
    instance-id: ${spring.application.name}:${random.uuid}

---
spring:
  config:
    activate:
      on-profile: docker
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
management:
  zipkin:
    tracing:
      endpoint: http://tracing-server:9411/api/v2/spans

---
spring:
  config:
    activate:
      on-profile: k8s

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    hostname: customers-service
    preferIpAddress: false
    instance-id: ${spring.application.name}:${random.uuid}

management:
  zipkin:
    tracing:
      endpoint: http://tracing-server:9411/api/v2/spans
