server:
  port: 9411

---
spring:
  config:
    activate:
      on-profile: default
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

---
spring:
  config:
    activate:
      on-profile: docker
eureka:
  client:
    serviceUrl:
      # Utilisation du service Kubernetes discovery-server
      defaultZone: http://discovery-server:8761/eureka/

---
spring:
  config:
    activate:
      on-profile: k8s

server:
  port: 9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    hostname: zipkin-server
    preferIpAddress: false
    instance-id: ${spring.application.name}:${random.uuid}
